oss:
  endpoint: "oss-cn-hongkong.aliyuncs.com"
  access_key_id: "YOUR_ACCESS_KEY_ID"
  access_key_secret: "YOUR_ACCESS_KEY_SECRET"
  bucket_name: "model-master"

server:
  max_workers: 2
  max_retries: 3
  retry_delay: 5
